version: '3.5'
services:
  web:
    build:
      context: ./src
    ports:
      - "5000:5000"
    depends_on:
      - db
    expose:
      - "5000"
    
    environment:
      SQLSERVER_HOST: "Server=db;Database=MyUserDatabase1;User=SA;Password=AlquidA@9826;"
      
    labels:
      - "SERVICE_5000_NAME=Authentication"
      - "SERVICE_TAGS=Authentication_Backend"
    volumes:
      - "/machine_config:/app/machine_config"
    networks: 
      - authentication-network

  db:
    image: "microsoft/mssql-server-linux"
    ports:
      - "1433"
    environment:
      SA_PASSWORD: "AlquidA@9826"
      ACCEPT_EULA: "Y"
    networks: 
      - authentication-network

networks: 
  authentication-network:
    name: potentiometer-network
    external: true        

